### PR TITLE
Updated pro-file to C++17 and fixed a bunch of warnings from g++, cla…

### PR DESCRIPTION
**Pull request by MartenBE**
Updated pro-file to C++17 and fixed a bunch of warnings from g++, clang++ and clang-tidy

I was looking to learn more about C++ and Qt through a project, and recently when I had to send a few files on my LAN, I stumbled on this. I would like to contribute more in the future, but I started out with just getting rid of some compiler/static analyzer warnings. Please code review this thoroughly as I am only starting out with C++ and Qt. I was also wondering how testing is best done for this application?

PS: I used the following script to build and analyze with clang/clang-tidy: 
[build.sh.txt](https://github.com/abdularis/LAN-Share/files/2851334/build.sh.txt)

### CODE REVIEW

**Comment by ZeroDot1** [comment]
Looks very good @abdularis should definitely add your updates.

**Comment by abdularis** [comment]
Can't build this commit

**Comment by MartenBE** [comment]
Could you provide me with the output, or is it possible to run the travis myself?

**Comment by abdularis** [comment]
https://travis-ci.org/abdularis/LAN-Share/builds/491980532

**Comment by MartenBE** [comment]
The new commit on my branch should fix the issue, but it seems new commits do not appear here anymore?

**Comment by abdularis** [comment]
which one

**Comment by abdularis** [comment]
you can create new PR

**Comment by MartenBE** [comment]
I'v created a new PR with the fix, so by merging #27 and #24, it should be fixed.
My apologies ofr the inconveniece, I am still figuring out how to work with travis locally to prevent this in the future

**Pull request merged**
